/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dns2.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "global.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static char **
_resolver_nombre_dns_1 (info_maquina  *argp, struct svc_req *rqstp)
{
	return (resolver_nombre_dns_1_svc(*argp, rqstp));
}

static int *
_registrar_equipo_dns_1 (info_maquina  *argp, struct svc_req *rqstp)
{
	return (registrar_equipo_dns_1_svc(*argp, rqstp));
}

static int *
_borrar_equipo_dns_1 (info_maquina  *argp, struct svc_req *rqstp)
{
	return (borrar_equipo_dns_1_svc(*argp, rqstp));
}

static int *
_modificar_equipo_dns_1 (info_maquina  *argp, struct svc_req *rqstp)
{
	return (modificar_equipo_dns_1_svc(*argp, rqstp));
}

static void
dns2prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		info_maquina resolver_nombre_dns_1_arg;
		info_maquina registrar_equipo_dns_1_arg;
		info_maquina borrar_equipo_dns_1_arg;
		info_maquina modificar_equipo_dns_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RESOLVER_NOMBRE_DNS:
		_xdr_argument = (xdrproc_t) xdr_info_maquina;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _resolver_nombre_dns_1;
		break;

	case REGISTRAR_EQUIPO_DNS:
		_xdr_argument = (xdrproc_t) xdr_info_maquina;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _registrar_equipo_dns_1;
		break;

	case BORRAR_EQUIPO_DNS:
		_xdr_argument = (xdrproc_t) xdr_info_maquina;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _borrar_equipo_dns_1;
		break;

	case MODIFICAR_EQUIPO_DNS:
		_xdr_argument = (xdrproc_t) xdr_info_maquina;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _modificar_equipo_dns_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	direcciones_dns_2 = new info_maquina[10];

	direcciones_dns_2[0].name = "DNS1";
	direcciones_dns_2[0].network = "red1";
	direcciones_dns_2[0].ip = "1.0";

	direcciones_dns_2[1].name = "DNS2";
	direcciones_dns_2[1].network = "red2";
	direcciones_dns_2[1].ip = "2.0";

	register SVCXPRT *transp;

	pmap_unset (DNS2PROG, DNS2VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DNS2PROG, DNS2VERS, dns2prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DNS2PROG, DNS2VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DNS2PROG, DNS2VERS, dns2prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DNS2PROG, DNS2VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
