/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cliente_dns.h"

bool_t
xdr_info_maquina (XDR *xdrs, info_maquina *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->network, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->ip, ~0))
		 return FALSE;
	return TRUE;
}
